// v0.7.0: register Clauge's custom #[tauri::command] functions with the
// Tauri 2 ACL so they can be invoked from the dashboard webview, which is
// loaded via `WebviewUrl::External(http://127.0.0.1:<port>/)`. Without an
// AppManifest, Tauri 2 rejects any custom (non-plugin) command coming from
// a non-local origin — see tauri-2.11.1/src/webview/mod.rs:1823 and the
// `remote_origin_blocked_for_custom_commands_without_app_manifest` test.
//
// Listing a command here causes `tauri_build` to autogenerate
// `allow-<command-kebab>` and `deny-<command-kebab>` permissions under
// `permissions/autogenerated/`. Those identifiers can then be referenced
// (bare, no prefix) from capabilities/main.json under `permissions`.
const APP_COMMANDS: &[&str] = &[
    "get_connection_status",
    "open_claude_ai_login",
    "signout_claude_ai",
    "has_claude_ai_session",
    "refresh_credentials",
    "wizard_complete",
    "wizard_skip",
    "restart_app",
    "check_for_updates",
];

fn main() {
    let app_manifest = tauri_build::AppManifest::new().commands(APP_COMMANDS);
    let attributes = tauri_build::Attributes::new().app_manifest(app_manifest);
    tauri_build::try_build(attributes).expect("tauri build script failed");
}
