// v0.7.0: register Clauge's custom #[tauri::command] functions with the
// Tauri 2 ACL so they can be invoked from the dashboard webview, which is
// loaded via `WebviewUrl::External(http://127.0.0.1:<port>/)`. Without an
// AppManifest, Tauri 2 rejects any custom (non-plugin) command coming from
// a non-local origin — see tauri-2.11.1/src/webview/mod.rs:1823 and the
// `remote_origin_blocked_for_custom_commands_without_app_manifest` test.
//
// Listing a command here causes `tauri_build` to autogenerate
// `allow-<command-kebab>` and `deny-<command-kebab>` permissions under
// `permissions/autogenerated/`. Those identifiers can then be referenced
// (bare, no prefix) from capabilities/main.json under `permissions`.
const APP_COMMANDS: &[&str] = &[
    "get_connection_status",
    "open_claude_ai_login",
    "signout_claude_ai",
    "has_claude_ai_session",
    "refresh_credentials",
    "wizard_complete",
    "wizard_skip",
    "restart_app",
    "check_for_updates",
    // v0.8.1: splash.js calls get_server_port for the fallback poll;
    // app.js calls take_pending_focus_connections to land on
    // Settings → Connections after wizard_complete. Both need to be
    // listed here so tauri-build autogenerates the allow-* permissions
    // referenced from capabilities/main.json.
    "get_server_port",
    "take_pending_focus_connections",
    "install_cli_symlink",
    // v0.9.0 Mac App Store flavor: three new IPCs gated by the cfg feature
    // flag. Listed unconditionally so DMG builds still register the no-op
    // variants (the frontend may probe is_mas_flavor on any build to gate UI).
    "is_mas_flavor",
    "grant_claude_dir_access",
    "has_claude_dir_bookmark",
    // v0.9.10 build 5: promoted from popover-only to app-level so the dashboard
    // (Settings) AND the onboarding wizard (Step 3 opt-in toggle) can drive
    // Launch at Login. On MAS these route to SMAppService (crate::autostart_mas);
    // on DMG/Windows to tauri-plugin-autostart. Required after making MAS
    // Launch-at-Login strictly opt-in (Apple Guideline 2.4.5(iii)).
    "set_autostart",
    "get_autostart",
];

fn main() {
    let app_manifest = tauri_build::AppManifest::new().commands(APP_COMMANDS);
    let attributes = tauri_build::Attributes::new().app_manifest(app_manifest);
    tauri_build::try_build(attributes).expect("tauri build script failed");
}
